version: '3'

volumes:
  prometheus_data:
  grafana_data:

networks:
  prometheus_network:

services:
  prometheus:
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus_network
    ports:
      - "9000:9090"

  grafana:
    image: grafana/grafana:latest
    ##environment:
    ##   - GF_INSTALL_PLUGINS=grafana-azure-monitor-datasource,sbueringer-consul-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - prometheus_network
    ports:
      - "9001:3000"
