version: '3.8'

volumes:
  rabbitmq-data-volume:
  rabbitmq-log-volume:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
      - rabbitmq-data-volume:/var/lib/rabbitmq
      - rabbitmq-log-volume:/var/log/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    ports:
      - ${MANAGEMENT_UI_HTTP_PORT:-8080}:15672
      - ${AMQP091_PORT:-5672}:5672
      - ${PROMETHEUS_PORT:-15692}:15692